### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ririko5834** [angrox/rpi-image-backup#1]
Dumping partition information
Dumping MBR
1+0 records in
1+0 records out
512 bytes copied, 0.0078523 s, 65.2 kB/s
Backup partitions
fsck from util-linux 2.37.2
e2fsck 1.46.5 (30-Dec-2021)
/dev/mmcblk0p1 is mounted.
e2fsck: Cannot continue, aborting.

File system check on partition /dev/mmcblk0p1 failed

So it cannot be used on running sbc?

**Comment by angrox** [comment]
Sorry, this is not possible with this script and not recommended. When you backup a mounted filesystem you would get an inconsistent backup - it would skip all open file handlers and of you would lose at least some transactions. 
This script is meant to remove the storage and make a dump of the whole system - as small as possible (do not backup empty sectors).

**Comment by ririko5834** [comment]
So how do I use it? Like where do I run it?
